BufferManager: added a periodic saving method and updated examples
robotology-playground/yarp-telemetry pull request #55
Opened 2021-01-29 15:34 UTC by AlexAntn

This PR introduces a periodic saving method to the BufferManager API. 

It runs in a thread that is activated periodically, checking the buffer to see if the amount of data currently stored crosses a specified threshold. If the threshold is crossed, the data is saved to a file, and the buffer is cleared and ready to accept more data.

This is a first step towards ensuring no data loss since we are now not bound by the size of the buffer. The file names are incremented at each save (so, e.g.: `buffer_test_0.mat`, `buffer_test_1.mat`, etc). 

The saving of the file is triggered if any channel crosses the data amount threshold. This ensures that the same .mat file corresponds to the same time-window, even if the number of entries between the channels doesn't match (e.g.: if the channels have different frequencies). 

One issue we found with the current implementation is the case where the save triggers just before a data push - this can lead to the loss of one entry, with the current buffer clearing. This could potentially be solved with a different buffer cleaning technique (instead of a full clear), or with the introduction of mutexes. 

Also, given the number of parameters being passed to the constructor, I and @Nicogene  have created a `BufferConfig` structure to encode these parameters, making it easier to initialize the `BufferManager`.

Addresses issue #47

2021-01-29 15:57 UTC, Nicogene requested changes

2021-01-29 15:57 UTC, Nicogene commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +                  m_threshold(_threshold), save_periodically(_save_periodically){*/
Maybe we may remove the old version

2021-01-29 15:57 UTC, Nicogene commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +    //size_t m_threshold{0};
We can remove also these one

2021-02-01 11:18 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +    void periodicSave()
I would suggest this to be ``private`` to avoid the user calling this manually.

2021-02-01 11:20 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +            std::this_thread::sleep_until(next_step);
Indentation issue

2021-02-02 13:25 UTC, Nicogene approved these changes

2021-02-02 13:29 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +                        saveToFile();
Maybe it is worth adding a mutex in ``saveToFile`` in case the user calls the method at the same time.

2021-02-02 13:44 UTC, Nicogene commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +                        saveToFile();
While working on it @AlexAntn and I discussed how to handle the concurrency.
As you pointed out the user can call `saveToFile()` while the thread is already executing the `saveToFile()` function and this a possible race condition.
Same thing if `push_back` is invoked and at the same time the `buff.clear()`  inside `saveToFile` is called by the thread spawn.
For sure we need a lock system, the first implementation may be simply using `std::mutex`
In the future we may think to a lock-free implementation, we can discuss how to handle concurrency during the next meeting

2021-02-02 13:48 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +                        saveToFile();
Sounds good! In any case, I am not sure if it is possible to save two ``mat`` files from two concurrent threads. This is something I have never investigated, so I am not sure if a lock-free implementation is entirely possible.

2021-02-03 09:00 UTC, AlexAntn commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +                        saveToFile();
I think, with the current implementation, the main issues would arise from 2 points: 

- when the buffer is being cleared (since the other thread might still be reading from the buffer);
- when it is writing the file itself (if both threads are writing the file at the same exact moment);

Both cases could be "fixed" with a mutex in the `saveToFile()` function, the only drawback I could see is some files in the sequence having only a single value (instead of the threshold used in the periodic saving). But then again, the user should never be calling the `saveToFile()` function I think? We can discuss it

2021-02-03 09:02 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +                        saveToFile();
> But then again, the user should never be calling the `saveToFile()` function I think? We can discuss it

If so, then the option to enable or disable the automatic saving would not make any sense.

2021-02-04 13:34 UTC, traversaro commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +};
As mentioned in the meeting, adding a single line of description for this parameters may be beneficial, as the meaning of things like `threshold` may not be obvious. Furthermore, I would either use the `m_` prefix for all the parameters, or not use it at all.

2021-02-04 13:36 UTC, traversaro commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +        auto ret = addChannels(channels);
Personal taste, so feel free to do as you @AlexAntn @Nicogene prefer, but in this case I think that using too much auto is a bit detrimental to readability, and having `bool ret`  may be more clear.

2021-02-04 13:38 UTC, traversaro commented on src/libYARP_telemetry/src/yarp/telemetry/BufferManager.h
> +                        saveToFile();
I think that disabling autosave to avoid that any thread is created may be useful in some cases. On the other hand, we can simply clarify that if autosave is enabled, `saveToFile`  does not works and it will return `false` .

2021-02-05 09:07 UTC, Nicogene commented
I was thinking to merge this PR as it is and open soon another PR addressing the remaining changes required + more improvements.

The upcoming PR will break probably the API once again 😅 

cc @GiulioRomualdi @S-Dafarra @traversaro @AlexAntn

2021-02-05 09:40 UTC, merged